repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.11.0
  hooks:
    - id: terraform_fmt
#    - id: terraform_docs  # not yet compatible with Terraform 0.12
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: check-merge-conflict
