style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/terraform-aws-modules/terraform-aws-vpc
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
